export const CONDITIONAL_ACTIONS = {
  SHOW: 'SHOW',
  HIDE: 'HIDE',
  ENABLE: 'ENABLE',
  DISABLE: 'DISABLE',
  MAKE_REQUIRED: 'MAKE_REQUIRED',
  MAKE_OPTIONAL: 'MAKE_OPTIONAL'
};

export const ACTION_LABELS = {
  [CONDITIONAL_ACTIONS.SHOW]: 'Show Field',
  [CONDITIONAL_ACTIONS.HIDE]: 'Hide Field',
  [CONDITIONAL_ACTIONS.ENABLE]: 'Enable Field',
  [CONDITIONAL_ACTIONS.DISABLE]: 'Disable Field',
  [CONDITIONAL_ACTIONS.MAKE_REQUIRED]: 'Make Required',
  [CONDITIONAL_ACTIONS.MAKE_OPTIONAL]: 'Make Optional'
};
